//! Derives the serving build stamp (riir-reflex build.rs pattern): the
//! COMPILED feature set from cargo's own `CARGO_FEATURE_*` exports
//! (nothing hand-types it) + the toolchain fingerprint inputs — rustc
//! version, commit hash, and host triple from `$RUSTC -vV`. The hosted
//! decision receipt (Proposal 014 §4) discloses both so a client running
//! the SAME release on the same platform class can re-derive and check;
//! cross-arch bit-identity is never claimed.

use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let mut feats: Vec<String> = std::env::vars()
        .filter(|(k, _)| k.starts_with("CARGO_FEATURE_"))
        .map(|(k, _)| {
            k["CARGO_FEATURE_".len()..]
                .to_ascii_lowercase()
                .replace('_', "-")
        })
        .collect();
    feats.sort();
    feats.dedup();
    let list = feats
        .iter()
        .map(|f| format!("    {f:?},"))
        .collect::<Vec<_>>()
        .join("\n");

    // The toolchain fingerprint inputs — probe the compiler that will
    // build this crate; a probe failure leaves the fields empty (the
    // receipt names the build, it never invents one).
    let mut release = String::new();
    let mut commit = String::new();
    let mut host = String::new();
    if let Ok(rustc) = std::env::var("RUSTC") {
        if let Ok(out) = Command::new(rustc).arg("-vV").output() {
            let text = String::from_utf8_lossy(&out.stdout);
            for line in text.lines() {
                if let Some(v) = line.strip_prefix("release: ") {
                    release = v.to_string();
                } else if let Some(c) = line.strip_prefix("commit-hash: ") {
                    commit = c.to_string();
                } else if let Some(h) = line.strip_prefix("host: ") {
                    host = h.to_string();
                }
            }
        }
    }

    let out = format!(
        "/// The COMPILED feature set + toolchain fingerprint inputs —\n\
         /// generated by build.rs (reflex's pattern); never hand-typed.\n\
         pub const COMPILED_FEATURES: &[&str] = &[\n{list}\n];\n\
         pub const RUSTC_RELEASE: &str = {release:?};\n\
         pub const RUSTC_COMMIT: &str = {commit:?};\n\
         pub const RUSTC_HOST: &str = {host:?};\n"
    );
    let out_dir = std::env::var("OUT_DIR").expect("cargo supplies OUT_DIR");
    std::fs::write(format!("{out_dir}/build_stamp.rs"), out).expect("write OUT_DIR/build_stamp.rs");
}
