// generated by riir-deploy — the Container fronting Worker
export default {
  async fetch(req, env) {
    const u = new URL(req.url);
return env.APP.fetch(req.url.replace(`https://${u.hostname}`, `http://127.0.0.1:8080`));
  },
};
